SportsStore/src/SportsStore.Web/Controllers/AdminController.cs
using SportsStore.Domain.Abstraction;
using SportsStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.Web.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private IProductRepo repository;

        public AdminController(IProductRepo repo)
        {
            repository = repo;
        }


        // GET: Admin
        public ViewResult Index()
        {
            return View(repository.Products);
        }

        public ViewResult Edit(int productId)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);
            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(Product product, HttpPostedFileBase image=null)
        {
            if (ModelState.IsValid)
            {
                if(image != null)
                {
                    product.ImageMimeType = image.ContentType;
                    product.ImageData = new byte[image.ContentLength];
                    //读取流：将数据从流传输到数据结构（如字节数组）中
                    image.InputStream.Read(product.ImageData, 0, image.ContentLength);
                }
                repository.SaveProduct(product);
                TempData["message"] = $"{product.Name}已经被保存！";
                return RedirectToAction("Index");
            }
            return View(product);
        }

        public ViewResult Create()
        {
            return View("Edit", new Product());
        }

        [HttpPost]
        public ActionResult Delete(int productId)
        {
            Product deletedP = repository.DeleteProduct(productId);
            if (deletedP != null)
            {
                TempData["message"] = $"{deletedP.Name}已经被删除！";
            }
            return RedirectToAction("Index");
        }
    }
}

SportsStore/src/SportsStore.Web/Controllers/ProductController.cs
using SportsStore.Domain.Abstraction;
using SportsStore.Domain.Entities;
using SportsStore.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.Web.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepo repo;
        public int PageSize { get; set; } = 3;
        public ProductController(IProductRepo r)
        {
            repo = r;
        }

        // GET: Product
        public ViewResult List(string category, int page =1)
        {
            //return View(repo.Products.OrderBy(p => p.ProductID).Skip((page - 1) * PageSize).Take(PageSize));
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = repo.Products.Where(p => category == null || p.Category == category)
                .OrderBy(p => p.ProductID).Skip((page - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems =  category==null? repo.Products.Count():repo.Products.Where(p=>p.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }

        public FileContentResult GetImage(int productId)
        {
            Product p = repo.Products.FirstOrDefault(a => a.ProductID == productId);
            if (p != null)
            {
                return File(p.ImageData, p.ImageMimeType);
            }
            return null;
        }
    }
}

SportsStore/src/SportsStore.Web/Views/Admin/Edit.cshtml
@model SportsStore.Domain.Entities.Product
@{
    ViewBag.Title = $"管理-编辑{Model.Name}";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

    <div class="panel">

        <div class="panel-heading">
            <h3>编辑 @Model.Name</h3>
        </div>

        @using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="panel-body">
                @Html.HiddenFor(m => m.ProductID)
                @foreach (var property in ViewData.ModelMetadata.Properties)
                {
                    switch (property.PropertyName)
                    {
                        case "ProductID":
                        case "ImageData":
                        case "ImageMimeType":
                            break;
                        default:
                            <div class="form-group">
                                <label>@(property.DisplayName??property.PropertyName)</label>
                                <br>
                                @if (property.PropertyName == "Description")
                                {
                                    @Html.TextArea(property.PropertyName, null, new { @class = "form-control", rows = 5 })
                                }
                                else
                                {
                                    @Html.TextBox(property.PropertyName, null, new { @class = "form-Control" })
                                }
                                @Html.ValidationMessage(property.PropertyName)
                            </div>
                            break;
                    }
                }

                <div class="form-group">
                    <div style="position:relative;">
                        <label>图像</label>
                        <a class="btn" href="javascript:;">
                            Choose File...
                            <input type="file" name="Image" size="40"
                                   style="position:absolute;z-index:2;top:0;left:0;filter:alpha(opacity=0);opacity:0;background-color:transparent;color:transparent;"
                                   onchange='$("#upload-file-info").html($(this).val());' />
                        </a>
                        <span class="label label-info" id="upload-file-info"></span>
                    </div>
                    @if (Model.ImageData == null)
                    {
                        <div class="form-control-static">没有图像</div>
                    }
                    else
                    {
                        <img class="img-thumbnail" width="150" height="150" src="@Url.Action("GetImage","Product",new { Model.ProductID })" />
                    }
                </div>

            </div>

            <div class="panel-footer">
                <input type="submit" value="保存" class="btn btn-primary" />
                @Html.ActionLink("取消", "Index", null, new { @class = "btn btn-default" })
            </div>
        }


    </div>


@*<h1>编辑 @Model.Name</h1>
@using (Html.BeginForm())
                {
                    @Html.EditorForModel()
                    <input type="submit" value="保存"/>
                    @Html.ActionLink("取消", "Index");
                }*@

SportsStore/src/SportsStore.Web/Views/Admin/Index.cshtml
@model IEnumerable<SportsStore.Domain.Entities.Product>

@{
    ViewBag.Title = "管理所有商品";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">

    <div class="panel-heading">
        <h3>所有商品</h3>
    </div>

    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">ID</th>
                <th>Name</th>
                <th class="text-right">Price</th>
                <th class="text-center">Actions</th>
            </tr>
            @foreach(var item in Model)
            {
                <tr>
                    <td class="text-right">@item.ProductID</td>
                    <td>@Html.ActionLink(item.Name,"Edit",new { item.ProductID })</td>
                    <td class="text-right">@item.Price.ToString("c")</td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete", "Admin"))
                        {
                            @Html.Hidden("ProductID",item.ProductID)
                            <input type="submit" class="btn btn-default btn-xs" value="删除"/>
                        }
                    </td>
                </tr>
            }
        </table>
    </div>

    <div class="panel-footer">
        @Html.ActionLink("添加新商品","Create",null, new { @class="btn btn-default" })
    </div>

</div>